/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserSettings = IDL.Record({
  'languagePreference' : IDL.Text,
  'voiceSpeed' : IDL.Float64,
  'voiceInputEnabled' : IDL.Bool,
  'ttsEnabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  'deleteUserSettings' : IDL.Func([], [], []),
  'getAllSettings' : IDL.Func([], [IDL.Vec(UserSettings)], ['query']),
  'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], []),
  'saveUserSettings' : IDL.Func([UserSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserSettings = IDL.Record({
    'languagePreference' : IDL.Text,
    'voiceSpeed' : IDL.Float64,
    'voiceInputEnabled' : IDL.Bool,
    'ttsEnabled' : IDL.Bool,
  });
  
  return IDL.Service({
    'deleteUserSettings' : IDL.Func([], [], []),
    'getAllSettings' : IDL.Func([], [IDL.Vec(UserSettings)], ['query']),
    'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], []),
    'saveUserSettings' : IDL.Func([UserSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };